### ISSUE TITLE
Add requirements.txt file

### ISSUE THREAD

**Issue by EdwardJXLi** [tommcn/Ottawa-Bus-Tracker#1]
Add a requirements file for easier development.

**Comment by tommcn** [comment]
@SuperZooper3 doesn't use a virtualenv so running`pip freze` wouldn't work. Also, the dependencies are:
 - sqlite3
 - flask 
 - werkzeug

**Comment by EdwardJXLi** [comment]
It would be also nice to include version numbers

**Comment by tommcn** [comment]
Super is working on a requirements.txt file

**Comment by tommcn** [comment]
We added a requirements file. Closing this issue
